dist: xenial
addons:
  apt:
    packages:
    - python3-pip
    - libegl1-mesa-dev
    - libxml-parser-perl
    - libxtst-dev
    - xutils-dev
    - libmount-dev
    - gperf
    - ninja-build
    - gobject-introspection
    - libgirepository1.0-dev
script:
    - sudo -H pip3 install --upgrade pip setuptools wheel
    - sudo -H pip3 install meson
    - ./bootstrap.sh manifest.txt
deploy:
  provider: releases
  api_key:
    secure: DMLbq9cWiDEcgpSzX5gSo00CDn1F72xV8SQMEN9lfVL14+LTulE3hKTf72+7e7pY/BAv6+aeatC3HDt2ySv1j1+obmUk6b8OCPN8wNL7ePTud6naYlgcDumJd1p/OoZ2DwlkRLz34cA9uWWv2y26KPUbd3pLLeBiECqz0l63EDEoX93okqMfZ5ortHqJVC5EmSvlq1o+tyH3sm99J852ATksEM9iQNAg1A2T/OM96SUMmyHgtozBSxmGCgqQT7dKakh8hnXoJk5aMa3Oaxfj06SVjE4ZE46vfSP2hOctDZ0YAaZEqZkkXv0R573549bWRBgXQx0uXyy6pWz3l/nkKXp7LAXUBY3Y4e2ZCh60ZT4Pc6i7Vzn3wpIHNm/Pn7v8nZ5XkcT7k7CphtLQK8qPMZOujgBew+qCE+PX3J3lPN1nkzUYVU0SUxVoJNibKt33Ye6m78Z3YsRqjJ7mJASxZKmahkZ+YjCblYssYZ2dvveztdawPCiS0yYY41DeA+h1Y7dkrG8bXvbbkYk4lHOZpksfmAQSI8MzDTQaQG4MWkCD20IqyU8vM+MzYeF0AXdVFTm/2nIGoEyKOgu7/HiuzV4vekXHf+pGrRjdikWU1YwaWGyrVsUFkmab/7qWzHgjfWvSaiZ5gHnuq6UK2HL5YanGYu2m152ltquPnCoXI3Y=
  file: deps.txz
  skip_cleanup: true
  on:
    tags: true
